import scipy.io as sio
import tensorflow as tf

weights = sio.loadmat("weights.mat")

def encoder_weights(train_w = False):
    return {
                'conv2d_0': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_0'],
                                        trainable=train_w, dtype=tf.float32, name="test_enc"),
                'conv2d_0b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_0b'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_2': tf.Variable(
                    weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_2'],
                    trainable=train_w, dtype=tf.float32),
                'conv2d_2b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_2b'],
                                         trainable=train_w, dtype=tf.float32),
                'conv2d_5': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_5'], trainable=train_w,
                                        dtype=tf.float32),
                'conv2d_5b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_5b'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_9': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_9'], trainable=train_w,
                                        dtype=tf.float32),
                'conv2d_9b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_9b'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_12': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_12'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_12b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_12b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_16': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_16'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_16b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_16b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_19': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_19'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_19b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_19b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_22': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_22'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_22b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_22b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_25': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_25'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_25b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_25b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_29': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_29'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_29b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_29b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_32': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_32'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_32b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_32b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_35': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_35'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_35b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_35b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_38': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_38'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_38b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_38b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_42': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_42'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_42b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_42b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_45': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_45'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_45b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_45b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_48': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_48'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_48b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_48b'], trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_51': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_51'], trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_51b': tf.Variable(weights['./tf-AdaIN-master/vgg_normalised.t7/conv2d_51b'], trainable=train_w,
                                          dtype=tf.float32)
            }


def decoder_weights(train_w = True):
    return {
                'conv2d_1': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_1'],
                                        trainable=train_w,
                                        dtype=tf.float32, name="conv2d_1"),
                'conv2d_1b': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_1b'],
                                         trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_5': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_5'],
                                        trainable=train_w,
                                        dtype=tf.float32),
                'conv2d_5b': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_5b'],
                                         trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_8': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_8'],
                                        trainable=train_w,
                                        dtype=tf.float32),
                'conv2d_8b': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_8b'],
                                         trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_11': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_11'],
                                         trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_11b': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_11b'],
                                          trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_14': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_14'],
                                         trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_14b': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_14b'],
                                          trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_18': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_18'],
                                         trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_18b': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_18b'],
                                          trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_21': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_21'],
                                         trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_21b': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_21b'],
                                          trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_25': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_25'],
                                         trainable=train_w,
                                         dtype=tf.float32),
                'conv2d_25b': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_25b'],
                                          trainable=train_w,
                                          dtype=tf.float32),
                'conv2d_28': tf.Variable(
                    weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_28'], trainable=train_w,
                    dtype=tf.float32),
                'conv2d_28b': tf.Variable(weights['./tf-AdaIN-master/decoder-content-similar.t7/conv2d_28b'],
                                          trainable=train_w,
                                          dtype=tf.float32)
            }